title: New York by Night Transcripts
description: An unofficial collection of transcripts for New York by Night, created by <a href="https://mqole.tumblr.com" target="_blank">mqole</a>.
url: "https://mqole.github.io/vtmTranscripts" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  sass_dir: _sass
  style: compressed
